### ISSUE TITLE
Cannot pass otherProps or html attributes to components

### ISSUE THREAD

**Issue by bigwoof91** [webalys-hq/streamline-wrapper-react#10]
👋 Really enjoying the wrapper y'all created for your giant icon library. I know the team is working on a major overhaul but wanted to flag something.

### The issue
In trying to pass some data attributes to the `StreamlineIcon` component, I found that this wasn't possible. Only defined props from `StreamlineIcon.propTypes` are passed to the component.

### The cause 
 Looking at source code, it looks like props are explicitly destructured and passed to the elements versus allowing `...otherProps` to be passed.

### The ask
It would be nice to be able to pass other props i.e. `alt` `title` `data-testid` The primary motivation for this is so that my team can write tests for _**our**_ component with a tool like [react testing library](https://testing-library.com/).

We can have work-arounds for now, but is not ideal for writing sufficient tests.

Thanks in advance for your help and consideration

**Comment by cbrwizard** [comment]
Thank you for your report, it totally makes sense.
In the following days however we will be releasing a new package which just stupidly provides svg files which can be customised using usual web practices. This means that this issue will be gone. 

The package is already released and it can be used with your npm token already https://github.com/webalys-hq/streamlinehq-npm. Feel free to try it out but consider it in beta. We will update our frontend and docs soon to explain how exactly to use it.

**Comment by cbrwizard** [comment]
Hello, we have just released a completely new universal npm package which is much more performant than before and solves all license sync issues. It requires a bit different setup but it's more straightforward. We know that migrating can be confusing but once it's done we believe it will provide better experience for you. I believe it will solve the issue you've mentioned as well.

Once you set it up you will be able to import the Streamline icons you own in a form of plain and simple svg files. This package will also not bloat your project with the files you don't need.

Please check it out here https://github.com/webalys-hq/streamlinehq-npm. If you have any issues for it or suggestions about it please open an issue there.
