### ISSUE TITLE
Large bundle size in icon packages

### ISSUE THREAD

**Issue by cbrwizard** [webalys-hq/streamline-wrapper-react#3]
Currently none of icon packages support tree-shaking which results in huge sizes of packages. This should be fixed. This has been reported by several customers as in https://github.com/webalys-hq/packages-issues/issues/5

**Comment by danielsunnerberg** [comment]
We're currently working around this issue by re-writing the exports using a Babel plugin: https://gitlab.com/lokalguiden/treeshakeable-streamline-icons/-/blob/master/index.js. This is fragile and very hacky but needed as the bundle size quickly becomes ridiculous without it.

**Comment by cbrwizard** [comment]
Oh yeah, I've played around with this approach a bit but didn't get any results. Were you able to reduce the bundle size?
Unfortunately I wasn't able to use your plugin, as I'm getting this error on build after following the package's readme:

<img width="1162" alt="Screenshot 2021-01-20 at 15 48 48" src="https://user-images.githubusercontent.com/1615659/105245185-2363bd00-5b37-11eb-9863-e3e20ef782d3.png">

Did I miss any extra dependencies? Also maybe that we have an old babel.

P.S. Optimizing npm packages is still a priority for us but we're focused on the checkout feature at the moment.

**Comment by kwesterfeld2** [comment]
@danielsunnerberg not sure how to use the babel plugin but that certainly is interesting to me.  I followed the instructions but nothing changed--and my app didn't break so obviously I'm missing something.  Can you provide instructions?

**Comment by danielsunnerberg** [comment]
The instructions are indeed quite vague, I didn't expect anyone to actually be interested :-).

@cbrwizard: Using the plugin makes it treeshakeable in our projects. We're using `babel/[cli|core]@7.12.10`. So far I've only used the plugin against the `streamline-regular` package, where all the icons are expected to reside in `lib`, e.g. `lib/arrows-diagrams/Arrows.js`. The plugin can then be used after adding it to `.babelrc` by running something like:
1. Clone `streamline-regular` to a new project and add the babel plugin
2. `yarn run babel ./lib -d ./dist`
3. `find lib/ -type f -name 'index.js' -exec rm {} \;` (not sure if this is needed)
4. rm -rf lib
5. mv dist lib

An important note is that the plugin is intended to be run on a project containing only a single streamline family (e.g. `streamline-regular`) and not on the project that's going to use the icons. You'll therefore need to host your own copy of the icons, which we're already doing to avoid rate-limiting issues.

The icons can then be referred to in the source project by e.g.
> import { IconLoveItSearch } from '@streamlinehq/streamline-regular/lib/social-medias-rewards-rating/LoveIt';

Note that the export name has a `Icon` prefix and that the path includes the icon group at the end as well, which doesn't match with the official documentation.

(cc @kwesterfeld2)

**Comment by kwesterfeld2** [comment]
@danielsunnerberg  this is great.  I'm not sure how we would "host a copy of the icons"--is there a git repo somewhere to clone?   Or did you simply unpack the npm package and perform the steps to prepare for export there?

**Comment by danielsunnerberg** [comment]
> @danielsunnerberg this is great. I'm not sure how we would "host a copy of the icons"--is there a git repo somewhere to clone? Or did you simply unpack the npm package and perform the steps to prepare for export there?

Exactly, we're simply unpacking the npm package contents and uploading it to a git repository. Fully aware that it's quite hacky, but it's better than including several megabytes of icons :shrug:.  (We also initially did this to avoid being rate limited while waiting for GItLab's cache layer to support private packages)

**Comment by danielsunnerberg** [comment]
I've now tested the Babel plugin against the Regular, Bold, Micro and Mini families and it seems to work fine. Some webpack chunks are now several megabytes smaller than before tree shaking.

**Comment by kwesterfeld2** [comment]
Ping....any updates?

**Comment by cbrwizard** [comment]
Hey, in the following days we will be releasing a new package which just stupidly provides svg files which can be customised using usual web practices. This means that this issue will be gone.

The package is already released and it can be used with your npm token already https://github.com/webalys-hq/streamlinehq-npm. Feel free to try it out but consider it in beta. We will update our frontend and docs soon to explain how exactly to use it.

**Comment by cbrwizard** [comment]
We have just released a completely new universal npm package which is much more performant than before and solves all license sync issues. It requires a bit different setup but it's more straightforward. We know that migrating can be confusing but once it's done we believe it will provide better experience for you. I believe it will solve the issue you've mentioned as well.

Once you set it up you will be able to import the Streamline icons you own in a form of plain and simple svg files. This package will also not bloat your project with the files you don't need.

Please check it out here https://github.com/webalys-hq/streamlinehq-npm. If you have any issues for it or suggestions about it please open an issue there.
