### ISSUE TITLE
Could not find a declaration file for module '@streamlinehq/streamline-bold/lib/interface-essential'

### ISSUE THREAD

**Issue by SkariDamm** [webalys-hq/streamline-wrapper-react#4]
It seems that the icon collection packages are missing type declarations. Do you have any plans to provide those?

![image](https://user-images.githubusercontent.com/2642407/105477681-17444080-5c9a-11eb-8e62-426784780c42.png)

**Comment by danielsunnerberg** [comment]
Semi unrelated, but perhaps it can be of some help: the Babel plugin mentioned in https://github.com/webalys-hq/streamline-wrapper-react/issues/3 also generated type declarations.

**Comment by bigwoof91** [comment]
Hello! 👋 Any news or update on this?

**Comment by cbrwizard** [comment]
Hey, we're working on a major overhaul of the npm packages right now to make them actually fucking usable for actual living people. This change will also solve this issue. Stay tuned

**Comment by cbrwizard** [comment]
Hello, we have just released a completely new universal npm package which is much more performant than before and solves all license sync issues. It requires a bit different setup but it's more straightforward. We know that migrating can be confusing but once it's done we believe it will provide better experience for you. I believe it will solve the issue discussed here as well.

Once you set it up you will be able to import the Streamline icons you own in a form of plain and simple svg files. This package will also not bloat your project with the files you don't need.

Please check it out here https://github.com/webalys-hq/streamlinehq-npm. If you have any issues for it or suggestions about it please open an issue there.
