### ISSUE TITLE
Warning: Encountered two children with the same key

### ISSUE THREAD

**Issue by philkeys** [webalys-hq/streamline-wrapper-react#7]
I am using the @streamlinehq/streamline-wrapper-react package and the @streamlinehq/streamline-light package.

I'm receiving this warning when importing certain icons from the Streamline Light npm package.

_Example import_
import { UV } from '@streamlinehq/streamline-light/lib/weather'
{UV.UvSun}

Warning: Encountered two children with the same key, `M16.25,17.5V22a1.5,1.5,0,0,1-3,0V17.5`. Keys should be unique so that components maintain their identity across updates. Non-unique keys may cause children to be duplicated and/or omitted — the behavior is unsupported and could change in a future version.

An icon that this didn't happen to was:

import { Arrows } from '@streamlinehq/streamline-mini-line/lib/interface-essential'
{Arrows.InterfaceArrowsRight}

I was wondering if there's certain things happening in the build process of the npm package.

**Comment by cbrwizard** [comment]
Thank you for the report, this indeed happens with some icons. We're aiming to resolve this issue in the next major update, which we're currently working on

**Comment by cbrwizard** [comment]
Hello, we have just released a completely new universal npm package which is much more performant than before and solves all license sync issues. It requires a bit different setup but it's more straightforward. We know that migrating can be confusing but once it's done we believe it will provide better experience for you. I believe it will solve the issue you've mentioned as well.

Once you set it up you will be able to import the Streamline icons you own in a form of plain and simple svg files. This package will also not bloat your project with the files you don't need.

Please check it out here https://github.com/webalys-hq/streamlinehq-npm. If you have any issues for it or suggestions about it please open an issue there.
